Repository erda-project/erda-actions, pull requests merged in 2021-09, with the labels that each got.

#176 update alpine and debian images
  dockerfiles/terminus-herd/herd.1.1.8-alpine-node.14.17/Dockerfile
  dockerfiles/terminus-herd/herd.1.1.8-debian-node.14.17/Dockerfile
  dockerfiles/terminus-nodejs/node.14.17.5/Dockerfile.alpine.npm.6.14
Labels: approved

#168 change testplan-run image
  actions/testplan-run/1.0/dice.yml
Labels: approved

#175 add docker login for some actions
  actions/gitbook/1.0/internal/pkg/build/execute.go
  actions/gitbook/1.0/internal/pkg/conf/conf.go
  actions/java-build/1.0/internal/pkg/build/execute.go
Labels: approved, kind/feature

#162 Add new error message for docker push
  actions/buildpack-aliyun/1.0/internal/run/build/build.go
  actions/buildpack-aliyun/1.0/internal/run/pack/pack.go
  actions/buildpack/1.0/internal/run/build/build.go
  actions/buildpack/1.0/internal/run/pack/pack.go
  actions/docker-push/1.0/internal/main.go
  actions/dockerfile/1.0/internal/pkg/build/execute.go
  actions/gitbook/1.0/internal/pkg/build/execute.go
  actions/golang/1.0/internal/pkg/build/build.go
  actions/java/1.0/internal/pkg/build/execute.go
  actions/js/1.0/internal/pkg/build/execute.go
  actions/php/1.0/internal/pkg/build/build.go
  actions/release/1.0/internal/pkg/migration.go
  pkg/docker/docker.go
Labels: approved, kind/feature

#180 support aab
  actions/release/1.0/internal/conf/conf.go
  actions/release/1.0/internal/pkg/app_parse.go
  actions/release/1.0/internal/pkg/execute.go
  actions/release/1.0/spec.yml
  go.mod
  go.sum
Labels: approved

#182 feature: rename registry from cn-hangzhou to erda.cloud
  actions/erda-pkg-release-public/1.0/dice.yml
Labels: approved

#185 Create pull_request_template.md
  .github/pull_request_template.md
Labels: approved

#187 update jsonparse docs
  actions/jsonparse/1.0/README.md
Labels: approved

#189 rollback mysql-cli spec
  actions/mysql-cli/1.0/spec.yml
Labels: approved

#190 java-dependency-check: update NVD; add custom configs
  Makefile
  actions/java-dependency-check/1.0/Dockerfile
  actions/java-dependency-check/1.0/internal/pkg/build/execute.go
  actions/java-dependency-check/1.0/internal/pkg/conf/conf.go
  actions/java-dependency-check/1.0/spec.yml
Labels: approved

#194 add securityContext
  actions/archive-release/1.0/dice.yml
  actions/archive-release/1.0/internal/config/config.go
  actions/archive-release/1.0/internal/repo/releasedyml.go
  actions/archive-release/1.0/internal/repo/releasedyml_test.go
  actions/archive-release/1.0/internal/repo/test_dice.yml
  actions/archive-release/1.0/spec.yml
  go.mod
  go.sum
Labels: approved

#184 fix does not return an error when docker push
  pkg/docker/docker.go
Labels: approved, bug

#195 app-create decode git username git password
  actions/app-create/1.0/dice.yml
  actions/app-create/1.0/internal/appCreate/appCreate.go
Labels: approved

#201 Feature/node
  dockerfiles/terminus-herd/herd.1.1.10-debian-node.12.22/Dockerfile
  dockerfiles/terminus-herd/herd.1.1.10-debian-node.12.22/deploy.sh
Labels: approved

#202 delete oss object recursively
  actions/archive-release/1.0/Dockerfile
  actions/archive-release/1.0/dice.yml
  actions/archive-release/1.0/internal/cmd/main.go
  actions/archive-release/1.0/internal/oss/oss.go
  actions/archive-release/1.0/internal/oss/oss_test.go
  actions/archive-release/1.0/internal/oss/progress.go
  actions/archive-release/1.0/internal/repo/releasedyml.go
  actions/archive-release/1.0/internal/repo/releasedyml_test.go
  actions/archive-release/1.0/internal/repo/repo.go
  pkg/metawriter/metawriter.go
Labels: approved, kind/bug

#205 android release bugfix
  actions/release/1.0/Dockerfile
  actions/release/1.0/dice.yml
  actions/release/1.0/internal/cmd/main.go
  actions/release/1.0/internal/pkg/execute.go
  actions/release/1.0/spec.yml
Labels: approved

#207 update action mem
  actions/add-nodes/1.0/dice.yml
  actions/upgrade-edge-cluster/1.0/dice.yml
Labels: approved

#208 set `innodb_large_prefix = on` for sandbox on msql 5.6
  actions/erda-mysql-migration/1.0-56/Dockerfile
  actions/erda-mysql-migration/1.0-56/dice.yml
  dockerfiles/erda-migration/sandbox56/Dockerfile
  dockerfiles/erda-migration/sandbox56/my.cnf
Labels: approved

#210 update erda-mysql-migration images: remove dll-reversing
  actions/erda-mysql-migration/1.0-56/dice.yml
  actions/erda-mysql-migration/1.0-57/dice.yml
  actions/erda-mysql-migration/1.0-80/dice.yml
  go.mod
  go.sum
Labels: approved

#186 update nodejs use docs, add dest_dir annotation
  actions/js-build/1.0/README.md
  actions/js/1.0/README.md
Labels: approved

#213 wait action executor
  actions/wait/1.0/README.md
  actions/wait/1.0/dice.yml
  actions/wait/1.0/spec.yml
Labels: approved

#214 update java-agent 1.4 version
  actions/buildpack-aliyun/1.0/sync_assets.sh
  actions/buildpack/1.0/sync_assets.sh
  actions/java-build/1.0/comp/download_spot_agent.sh
  actions/java/1.0/comp/download_spot_agent.sh
Labels: approved

#216 modify wait time param
  actions/wait/1.0/README.md
  actions/wait/1.0/spec.yml
Labels: approved

#217 change name of action testplan-run
  actions/testplan-run/1.0/spec.yml
Labels: approved
