Repository erda-project/erda-actions, pull requests merged in 2021-08, with the labels that each got.

#118 mysql-cli add sql print
  actions/mysql-cli/1.0/internal/pkg/build/execute.go
Labels: kind/feature

#119 mysql-cli add sql print
  actions/mysql-cli/1.0/dice.yml
Labels: kind/feature

#117 feature: update images: archive-release, erda-mysql-migration, erda-m…
  actions/archive-release/1.0/dice.yml
  actions/erda-mysql-migration-lint/1.0/dice.yml
  actions/erda-mysql-migration/1.0/dice.yml
Labels: approved

#120 update javaagent v1.1
  actions/buildpack/1.0/dice.yml
  actions/java-build/1.0/dice.yml
  actions/java/1.0/dice.yml
Labels: approved

#121 pipeline cancel should cancel app-run action pipelineID
  actions/app-run/1.0/Dockerfile
  actions/app-run/1.0/dice.yml
  actions/app-run/1.0/internal/appCancel/cancel/cancel.go
  actions/app-run/1.0/internal/appCancel/cmd/main.go
  actions/app-run/1.0/internal/appRun/appRun.go
  actions/app-run/1.0/internal/conf/conf.go
  actions/app-run/1.0/spec.yml
Labels: kind/feature

#123 feature: update erda migrator dependencies
  actions/erda-mysql-migration/1.0/internal/local/cmd/main.go
  actions/erda-mysql-migration/1.0/internal/local/config/configuration.go
  actions/erda-mysql-migration/1.0/spec.yml
  go.mod
  go.sum
Labels: approved, kind/feature

#124 agent report std error if match regexp
  actions/agent/1.0/dice.yml
Labels: kind/feature

#126 fix envs from
  actions/erda-mysql-migration/1.0/internal/local/config/configuration.go
Labels: approved, kind/feature

#128 update erda-mysql-migration image
  actions/erda-mysql-migration-lint/1.0/dice.yml
  actions/erda-mysql-migration/1.0/dice.yml
Labels: approved, kind/feature

#129 Update java action image
  actions/buildpack/1.0/dice.yml
  actions/java-build/1.0/dice.yml
  actions/java/1.0/dice.yml
Labels: approved

#130 java and buildpack action add JAVA_OPTS_ENABLED env to clear erda JAVA_OPTS
  actions/buildpack-aliyun/1.0/bp/java/pack/edas-dubbo-cnooc/start.sh
  actions/buildpack-aliyun/1.0/bp/java/pack/edas-dubbo/start.sh
  actions/buildpack-aliyun/1.0/bp/java/pack/edas/start.sh
  actions/buildpack-aliyun/1.0/bp/java/pack/springboot-asia/entrypoint.sh
  actions/buildpack-aliyun/1.0/bp/java/pack/springboot/entrypoint.sh
  actions/buildpack-aliyun/1.0/sync_assets.sh
  actions/buildpack/1.0/bp/java/pack/edas-dubbo-cnooc/start.sh
  actions/buildpack/1.0/bp/java/pack/edas-dubbo/start.sh
  actions/buildpack/1.0/bp/java/pack/edas/start.sh
  actions/buildpack/1.0/bp/java/pack/springboot-asia/entrypoint.sh
  actions/buildpack/1.0/bp/java/pack/springboot/entrypoint.sh
  actions/java/1.0/comp/openjdk/entrypoint.sh
  actions/java/1.0/comp/tomcat/entrypoint.sh
Labels: kind/feature

#138 add erda install package release cation
  Makefile
  actions/erda-pkg-release-enterprise/1.0/Dockerfile
  actions/erda-pkg-release-enterprise/1.0/README.MD
  actions/erda-pkg-release-enterprise/1.0/dice.yml
  actions/erda-pkg-release-enterprise/1.0/internal/bin/build
  actions/erda-pkg-release-enterprise/1.0/internal/bin/build.go
  actions/erda-pkg-release-enterprise/1.0/internal/cmd/main.go
  actions/erda-pkg-release-enterprise/1.0/internal/config/config.go
  actions/erda-pkg-release-enterprise/1.0/internal/pkg/env.go
  actions/erda-pkg-release-enterprise/1.0/internal/pkg/execute.go
  actions/erda-pkg-release-enterprise/1.0/internal/pkg/repo.go
  actions/erda-pkg-release-enterprise/1.0/pkg/env.go
  actions/erda-pkg-release-enterprise/1.0/pkg/metafile.go
  actions/erda-pkg-release-enterprise/1.0/pkg/oss.go
  actions/erda-pkg-release-enterprise/1.0/pkg/repo.go
  actions/erda-pkg-release-enterprise/1.0/pkg/utils.go
  actions/erda-pkg-release-enterprise/1.0/spec.yml
  actions/erda-pkg-release-public/1.0/Dockerfile
  actions/erda-pkg-release-public/1.0/README.MD
  actions/erda-pkg-release-public/1.0/dice.yml
  actions/erda-pkg-release-public/1.0/internal/bin/build_package.go
  actions/erda-pkg-release-public/1.0/internal/bin/build_package.sh
  actions/erda-pkg-release-public/1.0/internal/bin/compose.go
  actions/erda-pkg-release-public/1.0/internal/bin/compose.sh
  actions/erda-pkg-release-public/1.0/internal/cmd/main.go
  actions/erda-pkg-release-public/1.0/internal/config/config.go
  actions/erda-pkg-release-public/1.0/internal/pkg/env.go
  actions/erda-pkg-release-public/1.0/internal/pkg/execute.go
  actions/erda-pkg-release-public/1.0/internal/pkg/repo.go
  actions/erda-pkg-release-public/1.0/spec.yml
Labels: approved

#139 release action check application mode, project_service mode cannot ploy
  actions/release/1.0/internal/pkg/execute.go
  actions/release/1.0/spec.yml
Labels: approved

#140 change buildpack java release image
  actions/buildpack-aliyun/1.0/dice.yml
  actions/buildpack/1.0/dice.yml
  actions/java/1.0/dice.yml
  actions/release/1.0/dice.yml
Labels: approved

#141 update 3 actions images
  actions/erda-mysql-migration-lint/1.0/dice.yml
  actions/erda-mysql-migration/1.0/dice.yml
  actions/erda-pkg-release-enterprise/1.0/dice.yml
  actions/erda-pkg-release-enterprise/1.0/internal/bin/build
  go.mod
  go.sum
Labels: approved, kind/feature

#143 update erda-pkg-release-enterprise-action image
  actions/erda-pkg-release-enterprise/1.0/dice.yml
  actions/erda-pkg-release-enterprise/1.0/internal/bin/build.go
Labels: approved, kind/feature

#144 bugfix for json tag
  actions/reportengine/1.0/dice.yml
Labels: approved

#149 add Asynchronous ability for testplan-run action
  actions/testplan-run/1.0/internal/conf/conf.go
  actions/testplan-run/1.0/internal/testplan-run/testplan-run.go
  actions/testplan-run/1.0/spec.yml
Labels: approved, kind/feature

#151 mysql-cli remove return command run error
  actions/mysql-cli/1.0/internal/pkg/build/execute.go
Labels: bug

#155 upgrade go version
  Makefile
  actions/golang/1.0/Dockerfile
  dockerfiles/terminus-golang/Dockerfile
  dockerfiles/terminus-golang/build.sh
Labels: approved

#156 upgrade golang action image
  actions/golang/1.0/dice.yml
Labels: approved

#157 Fixed the issue that buildpack action does not output build-result
  actions/buildpack/1.0/internal/run/pack/pack.go
  actions/buildpack/1.0/internal/run/util/hashdir/hashdir.go
Labels: approved, bug

#164 add 1.3 version java agent
  actions/buildpack/1.0/sync_assets.sh
  actions/java-build/1.0/comp/download_spot_agent.sh
  actions/java/1.0/comp/download_spot_agent.sh
Labels: approved

#161 Added a field to continue execution after failure in testplan-action
  actions/testplan-run/1.0/internal/conf/conf.go
  actions/testplan-run/1.0/internal/testplan-run/testplan-run.go
  actions/testplan-run/1.0/spec.yml
Labels: bug

#165 upgrade java buildpack build image
  actions/buildpack/1.0/dice.yml
  actions/java-build/1.0/dice.yml
  actions/java/1.0/dice.yml
Labels: approved

#150 update testplan-run mirror
  actions/testplan-run/1.0/dice.yml
Labels: kind/feature

#171 feature: upgrade nvm and default node versions, add debian and alpine…
  actions/js-build/1.0/Dockerfile
  actions/js-build/1.0/internal/pkg/build/execute.go
  dockerfiles/terminus-herd/herd.1.1.8-alpine-node.14.17/Dockerfile
  dockerfiles/terminus-herd/herd.1.1.8-alpine-node.14.17/deploy.sh
  dockerfiles/terminus-herd/herd.1.1.8-debian-node.14.17/Dockerfile
  dockerfiles/terminus-herd/herd.1.1.8-debian-node.14.17/deploy.sh
  dockerfiles/terminus-nodejs/node.14.17.5/Dockerfile.alpine.npm.6.14
  dockerfiles/terminus-nodejs/node.14.17.5/Dockerfile.debian.npm.6.14
Labels: approved
