Repository erda-project/erda-actions, pull requests merged in 2021-07, with the labels that each got.

#71 change app run, app create, assert action dice.yml image
  actions/app-create/1.0/dice.yml
  actions/app-run/1.0/dice.yml
  actions/assert/1.0/dice.yml
Labels: approved

#81 reportengine support namespaced erda
  actions/reportengine/1.0/dice.yml
  actions/reportengine/1.0/spec.yml
Labels: approved

#83 dice-action: fix conf
  actions/dice/1.0/internal/dice/conf.go
Labels: approved

#84 dice-action: update image
  actions/dice/1.0/dice.yml
Labels: approved

#87 feature: update archive-release and erda-mysql-migration image
  actions/archive-release/1.0/dice.yml
  actions/erda-mysql-migration/1.0/dice.yml
Labels: approved

#80 update app run image
  actions/app-run/1.0/dice.yml
Labels: approved

#89 feature: to support custom oss directory
  actions/archive-release/1.0/internal/config/config.go
  actions/archive-release/1.0/spec.yml
Labels: approved

#90 assert and jsonparse action use stdOutput
  actions/assert/1.0/internal/pkg/build/execute.go
  actions/jsonparse/1.0/internal/pkg/build/execute.go
Labels: approved

#88 app-create add branch choose push input, encode git pull username and password
  actions/app-create/1.0/internal/appCreate/appCreate.go
  actions/app-create/1.0/internal/conf/conf.go
  actions/app-create/1.0/spec.yml
Labels: approved

#91 feature: to support custom oss directory for archive-extensions
  actions/archive-extensions/1.0/internal/config/config.go
  actions/archive-extensions/1.0/spec.yml
Labels: approved

#92 feature: update archive-extensions and archive-release images
  actions/archive-extensions/1.0/dice.yml
  actions/archive-release/1.0/dice.yml
Labels: approved, kind/feature

#93 api-test spec add executor field
  actions/api-test/2.0/spec.yml
Labels: approved

#98 feature: fix the log of requesting dicehub
  actions/push-extensions/1.0/internal/client/client.go
Labels: approved

#103 feature: add erda-mysql-migration-liint
  Makefile
  actions/erda-mysql-migration-lint/1.0/Dockerfile
  actions/erda-mysql-migration-lint/1.0/README.md
  actions/erda-mysql-migration-lint/1.0/dice.yml
  actions/erda-mysql-migration-lint/1.0/internal/cmd/main.go
  actions/erda-mysql-migration-lint/1.0/internal/config/config.go
  actions/erda-mysql-migration-lint/1.0/spec.yml
  go.mod
  go.sum
Labels: approved

#104 feature: update images for erda-mysql-migration and erda-mysql-migration-lint
  actions/erda-mysql-migration-lint/1.0/dice.yml
  actions/erda-mysql-migration-lint/1.0/internal/cmd/main.go
  actions/erda-mysql-migration-lint/1.0/internal/config/config.go
  actions/erda-mysql-migration/1.0/dice.yml
  go.sum
Labels: approved

#109 feature: update migration dependencies
  actions/erda-mysql-migration/1.0/Dockerfile
  go.mod
  go.sum
Labels: approved

#110 change spot-agent.jar readme info
  actions/java-build/1.0/README.md
  actions/release/1.0/README.md
Labels: documentation, kind/feature

#107 add testplan-run action
  Makefile
  actions/testplan-run/1.0/Dockerfile
  actions/testplan-run/1.0/README.md
  actions/testplan-run/1.0/dice.yml
  actions/testplan-run/1.0/internal/cmd/main.go
  actions/testplan-run/1.0/internal/conf/conf.go
  actions/testplan-run/1.0/internal/testplan-run/run.go
  actions/testplan-run/1.0/internal/testplan-run/testplan-run.go
  actions/testplan-run/1.0/spec.yml
Labels: kind/feature

#114 feature: delete git ref path from OSS before uploading
  actions/archive-release/1.0/internal/cmd/main.go
  actions/archive-release/1.0/internal/config/config.go
  actions/archive-release/1.0/internal/oss/oss.go
  actions/erda-mysql-migration-lint/1.0/internal/cmd/main.go
  actions/erda-mysql-migration-lint/1.0/internal/config/config.go
  actions/erda-mysql-migration-lint/1.0/spec.yml
  actions/erda-mysql-migration/1.0/internal/action/cmd/main.go
  actions/erda-mysql-migration/1.0/internal/action/migration/config.go
  actions/erda-mysql-migration/1.0/internal/local/config/configuration.go
  actions/erda-mysql-migration/1.0/spec.yml
  go.mod
  go.sum
Labels: approved

#116 feature: fix mysql client character error
  actions/erda-mysql-migration/1.0/Dockerfile
  actions/erda-mysql-migration/1.0/my.cnf
Labels: approved, bug
