Repository erda-project/erda-actions, pull requests merged in 2021-11, with the labels that each got.

#233 feature: add erda-action extension image format check
  .github/workflows/image-check.yml
  actions/reportengine/1.0/dice.yml
  actions/virtual-offline-image/1.0/dice.yml
Labels: approved

#245 git checkout 833cd49a186b52d13ce327f09dbe75ba449c9d05 actions/archive…
  actions/archive-release/1.0/Dockerfile
  actions/archive-release/1.0/internal/cmd/main.go
  actions/archive-release/1.0/internal/oss/oss.go
  actions/archive-release/1.0/internal/repo/releasedyml.go
  actions/archive-release/1.0/internal/repo/releasedyml_test.go
  actions/archive-release/1.0/internal/repo/repo.go
Labels: approved

#247 update mobile template version
  actions/mobile-template/1.0/Dockerfile
  actions/mobile-template/1.0/dice.yml
Labels: approved

#250 fix: git-checkout action downgrade alpine version for dns issue
  actions/git-checkout/1.0/Dockerfile
  actions/git-checkout/1.0/dice.yml
Labels: approved

#255 rebuild php action image
  actions/php/1.0/dice.yml
Labels: approved

#258 not trim charset utf8,utf8mb4 while parsing create table stmt
  actions/erda-mysql-migration/1.0-56/Dockerfile
  actions/erda-mysql-migration/1.0-56/dice.yml
  actions/erda-mysql-migration/1.0-57/Dockerfile
  actions/erda-mysql-migration/1.0-57/dice.yml
  actions/erda-mysql-migration/1.0-57/internal/local/config/configuration.go
  actions/erda-mysql-migration/1.0-80/Dockerfile
  actions/erda-mysql-migration/1.0-80/dice.yml
  dockerfiles/erda-migration/sandbox56/Dockerfile
  dockerfiles/erda-migration/sandbox57/Dockerfile
  dockerfiles/erda-migration/sandbox80/Dockerfile
  pkg/envconf/load.go
  pkg/envconf/load_test.go
Labels: approved, kind/feature

#266 upgrade golang action docker cli
  actions/golang/1.0/dice.yml
Labels: approved

#270 add contrast security action
  Makefile
  actions/contrast-security/1.0/Dockerfile
  actions/contrast-security/1.0/README.md
  actions/contrast-security/1.0/cmd/main.go
  actions/contrast-security/1.0/dice.yml
  actions/contrast-security/1.0/internal/pkg/build/execute.go
  actions/contrast-security/1.0/internal/pkg/conf/conf.go
  actions/contrast-security/1.0/spec.yml
Labels: approved

#273 action-agent: fix callback speed issue
  actions/agent/1.0/dice.yml
Labels: enhancement, kind/bug

#271 email action
  Makefile
  actions/email/1.0/Dockerfile
  actions/email/1.0/README.md
  actions/email/1.0/dice.yml
  actions/email/1.0/internal/cmd/main.go
  actions/email/1.0/internal/pkg/build/execute.go
  actions/email/1.0/internal/pkg/conf/conf.go
  actions/email/1.0/spec.yml
Labels: approved

#274 update contract secuirty public and category
  actions/contrast-security/1.0/spec.yml
  actions/email/1.0/dice.yml
Labels: approved

#277 contrast security add limit
  actions/contrast-security/1.0/dice.yml
  actions/contrast-security/1.0/internal/pkg/build/execute.go
Labels: approved

#279 Feature/support pkg version
  actions/erda-pkg-release-enterprise/1.0/Dockerfile
  actions/erda-pkg-release-enterprise/1.0/dice.yml
  actions/erda-pkg-release-enterprise/1.0/pkg/oss.go
Labels: approved

#281 Feature/support release migration
  actions/release/1.0/dice.yml
  actions/release/1.0/internal/conf/conf.go
  actions/release/1.0/internal/pkg/execute.go
  actions/release/1.0/internal/pkg/migration.go
  actions/release/1.0/internal/pkg/migration_erda.go
  actions/release/1.0/internal/pkg/release.go
Labels: approved

#282 feat: move erda release enterprise to enterprise repo
  actions/erda-pkg-release-enterprise/1.0/Dockerfile
  actions/erda-pkg-release-enterprise/1.0/README.MD
  actions/erda-pkg-release-enterprise/1.0/dice.yml
  actions/erda-pkg-release-enterprise/1.0/internal/bin/build
  actions/erda-pkg-release-enterprise/1.0/internal/bin/build.go
  actions/erda-pkg-release-enterprise/1.0/internal/cmd/main.go
  actions/erda-pkg-release-enterprise/1.0/internal/config/config.go
  actions/erda-pkg-release-enterprise/1.0/internal/pkg/env.go
  actions/erda-pkg-release-enterprise/1.0/internal/pkg/execute.go
  actions/erda-pkg-release-enterprise/1.0/internal/pkg/repo.go
  actions/erda-pkg-release-enterprise/1.0/pkg/env.go
  actions/erda-pkg-release-enterprise/1.0/pkg/metafile.go
  actions/erda-pkg-release-enterprise/1.0/pkg/oss.go
  actions/erda-pkg-release-enterprise/1.0/pkg/repo.go
  actions/erda-pkg-release-enterprise/1.0/pkg/utils.go
  actions/erda-pkg-release-enterprise/1.0/spec.yml
Labels: approved, kind/feature
